const personEnumerators = {
  gender: [
    'Male',
    'Female',
  ],
  roleInHousehold: [
    'Son',
    'Daughter',
    'Father',
    'Mother',
    'Kaka',
    'Mama',
    'Kaki',
    'Mami',
    'Mashi',
    'Mesho',
    'Chacha',
    'Chachi',
    'Dadu',
    'Dida',
    'Thakurda',
    'Thakuma',
    'Cousin',
    'Other',
  ],
  educationLevel: [
    'PrimarySchool',
    'MiddleSchool',
    'SecondarySchool',
    'HigherSecondary',
    'College',
    'Other',
  ],
  primaryJob: [
    'Student',
    'Housewife',
    'Farmer',
    'ConstructionLaborer',
    'HouseMaid',
    'Other',
  ],
  alternateLivelihood: [
    'Student',
    'Housewife',
    'Farmer',
    'Construction',
    'Fishing',
    'Other',
  ],
};

export default personEnumerators;
